### ISSUE TITLE
No lines with coverage information in this diff.

### ISSUE THREAD

**Issue by sunmoondeer** [Bachmann1234/diff-cover#104]
I get the xml file according to invoke the jacoco api, the code like this:

final XMLFormatter xmlFormatter = new XMLFormatter();
final IReportVisitor xmlVisitor = xmlFormatter
    .createVisitor(new FileOutputStream("D:/work/test/jacoco/codecoverage/xxx/aaa.xml"));
  xmlVisitor.visitInfo(execFileLoader.getSessionInfoStore().getInfos(),
    execFileLoader.getExecutionDataStore().getContents());
  xmlVisitor.visitBundle(bundleCoverage, new DirectorySourceFileLocator(
    sourceDirectory, "utf-8", 4));
  xmlVisitor.visitEnd();

And I went to the D:/work/test/jacoco/codecoverage/xxx directoy run diff-cover command, I received 
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff. This directory contains the source files

where shoud i run this commond?

**Comment by sunmoondeer** [comment]
I can get the diff info according to run git diff origin/master...HEAD. But when I run diff-cover report.xml --html-report report.html, I get the No lines with coverage information in this diff

**Comment by pikuldorota** [comment]
Hi,
I've run into same issue. I believe problem lies in `XmlCoverageReporter_measured_source_path_matches(self, package_name, file_name, src_path)` function. It compares paths from jacoco and git command by simple string comparison. When the tool is run on windows platform it gets windows style path from jacoco and unix style path from git. What's even worse in this case is that this function `GitDiffReporter.src_paths_changed(self)` changes all paths to lowercase (ex. **"src\\main\\Fantastic_file.groovy"** vs **"src/main/fantastic_file.groovy"**).
I think but I haven't tested it in this library that changing comparison to `os.path.samefile(path1, path2)` function and removing lowering may help in this case. However as I'm new to this library (and haven't tested it yet) I can't guarantee that it won't destroy something.
Also keep in mind that jacoco report has to have paths relative to main directory where git is.

**Comment by Bachmann1234** [comment]
It's seems plausible to be that a coverage file with Windows paths is not being normalized properly.

That being said I thought we had at least a few people using this tool on Windows systems...

But I am not going to be in a position to look into this for a while. Someone is able to track this down and make a PR I can look at it when I get back.

If no one does I'll take a look when I can find some time.

**Comment by sunmoondeer** [comment]
Change to linux env and bug fixed. Thanks
