### ISSUE TITLE
Wondering why `diff-cover` uses three dot notation for the diff

### ISSUE THREAD

**Issue by nicoddemus** [Bachmann1234/diff-cover#105]
Hi,

We have integrated `diff-cover` into our workflow at work by making jobs publish `diff-cover` comments into the PR for a branch, including links and emojis (we use BitBucket Server). 

Works great, here's a quick screenshot:

![image](https://user-images.githubusercontent.com/1085180/58274423-38d48280-7d69-11e9-90c6-83103d5c540f.png)

So thanks a lot for the great tool!

--- 

Now I would like to describe a problem we are having, and later discuss a couple of possible solutions.

On occasion we work with long lived topic branches. Those are topic branches which will be around for some time (say a month) while a large feature is being worked on. From those long lived topic branches we then create short lived topic branches for smaller amounts of work (for example, a short lived branch to work on the application business logic, then another one after that to work on the GUI, and so on). Then we open PRs to merge the short lived branches into the long lived one.

It happens that we want to get some update from `master` in both the long lived branch and into its short lived branches. Those changes that come from `master` won't appear in the PR from `short topic` -> `long topic`, as BitBucket will only show the changes that are in `short topic` and not on `long topic`, even if they came from somewhere else.

And here we noticed a problem: a few files are being reported as not being fully covered by `diff-cover`, but they are not even shown in our tree of "changed files" on the PR in BitBucket: it is the case with the `test_grid_table_editor.py` in the previous screenshot. This is confusing as we don't really know what to do to fix the coverage, as the file is not even visible to us on the PR.

Digging into the code, I noticed [`diff-cover` uses](https://github.com/Bachmann1234/diff-cover/blob/master/diff_cover/git_diff.py#L33) [three-dot range notation](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-Theem82308203emthree-dotSymmetricDifferenceNotation) to obtain the patch for the PR.

When using the three dot notation, the commit history is taken in account to produce the patch, including commits which are in both branches but are not in the actual patch that will be applied by the merge.

The other common notation used with `git diff` is [two-dot range notation](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-Theememtwo-dotRangeNotation), which only shows the full patch between the two branch tips: a plain diff between the trees, regardless of the commit history. 

Another way to explain this:

1. Branch `long` is created from `master`.
2. Branch `short` is created from `big`.
3. A new function, with 0% code coverage, is committed to `master` into commit `ABAB`.
4. `master` is merged into `long` **and** `short`, so both branches now contain the commit `ABAB`.

With two-dot notation, the code coverage for the `short -> long` merge shows nothing (that's the exact patch between them).

With three-dot notation, the code coverage for the `short -> long` merge will show the function with 0% coverage, even thought it was not added by the developers of either `long` or `short` branches, coming from `master` (of course it should have been covered in the first place, but that's beside the point).

IMHO the two-dot notation makes more sense for `diff-cover`, this way developers only worry about the actual lines being changed by them (which codecov.io calls "patch coverage"), which I believe is one of the selling points of using `diff-cover`. :grin:

---

Having said all that (and sorry about the long post), I see some solutions:

1. Change `diff-cover` to use two-dot notation. This is simplest, but I'm not sure how workflow works, and it would break use cases where the `diff-cover` notation makes sense.
2. Make a `--diff-notation=two/three` (or similar) option that lets the (advanced) user choose which method to use to obtain the patch.
3. Restart the work in #26 and let the user provide a patch file, bypassing the actual call to `git diff`.

What do you guys think? I'm happy to contribute a PR with whatever solution you deem best.

Thanks!

**Comment by nicoddemus** [comment]
cc @gcardozo123

**Comment by Bachmann1234** [comment]
Howdy!

So I actually appreciate the context and detail. I wanted to get that out there first :-)

As the answer to your question I don't actually know. I was not the original author but I have been maintaining this for a while now.


That being said this makes a lot of sense. *To protect backwards compatibility I think this feature should be added as a flag.*

But it will be some time before I can get to it. I'm currently on my honeymoon and start a new job when I get home so I am going to need at least a little time to settle in. 

But this seems like a solid addition if anyone sees this and wants to open a PR for it I can probably review it when I get back. I don't expect it would be a terribly difficult Pr

Otherwise I'll take a look at adding this when things clear up a bit.

**Comment by Bachmann1234** [comment]
Hmm.... Actually .. does @wedaly pay attention to GitHub notifications?!

He was the original author and may actually know the answer to this

**Comment by nicoddemus** [comment]
Thanks @Bachmann1234 for the prompt reply and congratulations on your marriage.

I will work on adding the option then: as you mention, it should be simple to do so. 👍

**Comment by wedaly** [comment]
I don't remember either :)  I suspect that I just knew less about git at the time, and the three-dot notation worked for the way we did branching at EdX.

**Comment by Bachmann1234** [comment]
See https://pypi.org/project/diff-cover/2.1.0/

**Comment by StruggleYang** [comment]
good.i need it
