### ISSUE TITLE
`from lazy import lazy` is broken in Python 3.5

### ISSUE THREAD

**Issue by dashea** [Bachmann1234/diff-cover#24]
3.5 changed the semantics of import a little bit, one result being that the way lazy sets itself up is no longer what is expected. `from lazy import lazy` ends up with the module lazy.lazy loaded as "lazy" instead of the class within that module, and diff-cover now crashes with "TypeError: 'module' object is not callable"

I've opened a PR to fix lazy at https://github.com/stefanholek/lazy/pull/3 but the project is kind of a ghost town it seems, so I'm not sure how it should best be handled.

**Comment by Bachmann1234** [comment]
Thanks for the heads up. Ill try to look into this asap. Lazy came into the project before I took it over so I gotta experiment a bit with it. Im a little frustrated my tests are not picking it up... im guessing tox does not have 3.5 in there.

**Comment by Bachmann1234** [comment]
Ah, yeah... its not there. Ok. ill add it and fix this sometime this week. Maybe even tonight. No promises though

**Comment by Bachmann1234** [comment]
@dashea try out 0.8.5 

I just dropped lazy as it was not used too much and it was not too hard to just.... do it.

**Comment by dashea** [comment]
Perfect, thanks.
