### ISSUE TITLE
if the absolute path of the git repository have a blank space, the git_root in diff_cover\git_path.py will be wrong

### ISSUE THREAD

**Issue by backupProject** [Bachmann1234/diff-cover#27]
Currently, the git_root in diff_cover\git_path.py is as follow:
[ver 0.8.5] 
line- 68 git_root = stdout.split()[0] if stdout else u''

if the absolute path of the git repository have a blank space, for example, 
it is "C:\Users\Work Module\test", git_root will be "C:\Users\Work", but git_root should be "C:\Users\Work Module\test" in fact.

I think the code should be git_root = stdout.split('\n')[0] if stdout else u'', because the sdout of "git rev-parse --show-toplevel --encoding=utf-8" should be separated by a line break not a blank space.

**Comment by Bachmann1234** [comment]
I will take a look asap. Thanks for letting me know

**Comment by backupProject** [comment]
It is my pleasure.

**Comment by Bachmann1234** [comment]
Should be fixed in https://pypi.python.org/pypi/diff_cover/0.8.6
