### ISSUE TITLE
Option to use external CSS

### ISSUE THREAD

**Issue by mgedmin** [Bachmann1234/diff-cover#34]
Jenkins sets a restrictive content security policy that forbids inline CSS.  This means diff-cover reports in my Jenkins workspace are basically unreadable: https://issues.jenkins-ci.org/browse/JENKINS-32590

![ekrano nuotrauka is 2016-01-25 11-12-30](https://cloud.githubusercontent.com/assets/159967/12547441/25f42972-c359-11e5-84c5-97c672da55f4.png)

What do you think about a command-line option `--external-css=style.css` that would write a separate `style.css` file and put a `<link rel="stylesheet" href="style.css">` instead of the inline `<style>...</style>` in the generate HTML?

I could create a pull request, if you think adding such a workarund into diff-cover is reasonable.

**Comment by Bachmann1234** [comment]
If you are willing to make the PR I will review and likely merge if the code is ok and has tests.

I like the idea.

You should know the code on master has not been released yet so if the PR comes soon it may be delayed a bit until I hear back from someone testing it. I plan on releasing master some time in early February no matter what though.
