### ISSUE TITLE
don't do logging.basicConfig on import

### ISSUE THREAD

**Issue by agroszer** [Bachmann1234/diff-cover#42]
see https://github.com/Bachmann1234/diff-cover/blob/master/diff_cover/tool.py#L48

```
import logging
logging.basicConfig(format='%(message)s')
LOGGER = logging.getLogger(__name__)
```

Packages that import this module need to work around that.
Rather call basicConfig in main()

**Comment by Bachmann1234** [comment]
Ok, that should be an easy enough fix

I'll try and get it tonight

**Comment by Bachmann1234** [comment]
Fixed in https://github.com/Bachmann1234/diff-cover/commit/433161ac70f338f4bceb8b20e20e9dfecc516cc6

https://pypi.python.org/pypi/diff_cover/0.9.4
