### ISSUE TITLE
stop checking tool installation by importing it

### ISSUE THREAD

**Issue by agroszer** [Bachmann1234/diff-cover#44]
linters are anyway executed in a subprocess, a subprocess works without the linter being importable by python

**Comment by Bachmann1234** [comment]
Fair enough. Diff-cover could check for the tools by calling a basic subprocess and checking the status code of that process. 

Implementing this I think I will prefer trying importing followed by running the command since subprocess is comparatively expensive. But ill try and look at this soon

**Comment by Bachmann1234** [comment]
Looking at the code this is what we are doing for JS based tools. Would not be too hard for the python ones. No promises but maybe this weekend.

**Comment by Bachmann1234** [comment]
Code for this is on master. I am going to run a couple tests before releasing it though. I think ill release tomorrow

**Comment by Bachmann1234** [comment]
Released https://pypi.python.org/pypi/diff_cover/0.9.6 

I saw your comments on the commit and they should be addressed.
