### ISSUE TITLE
diff-quality checks only the first modified file

### ISSUE THREAD

**Issue by fperrin** [Bachmann1234/diff-cover#47]
Hi,

When running `diff-quality --violations pyflakes --compare-branch master` (i.e. letting diff-quality run pyflakes itself), only the first modified file is checked.

To reproduce:
```
git clone git@github.com:fperrin/diff-cover-issue-demo.git
cd diff-cover-issue-demo/
git checkout check_only_first 
diff-quality --violations pyflakes 
```
This reports only the issue in hello.py, but if you `git diff master..` it's obvious you should have a warning in hi.py too.

I think the problem is in violationsreporter.base.QualityReporter.violations; after checking the first file, self.reports is set, so when violations() is called on the second file, it does nothing.

**Comment by Bachmann1234** [comment]
Ill try and get a look at this over the weekend, thanks!

**Comment by Bachmann1234** [comment]
Howdy! 

Just wanted to report I have tracked down the bug. Seems like my test suite is biased towards passed in reports.

While I figure out a good fix (if you need a workaround) you can pass in a report
```
(venv) ~/code/diff-cover-issue-demo   check_only_first  diff-quality --violations pyflakes report.txt
-------------
Diff Quality
Quality Report: pyflakes
Diff: origin/master...HEAD, staged, and unstaged changes
-------------
hello.py (0.0%):
    2: undefined name 'unknown_var'
hi.py (0.0%):
    2: undefined name 'unknown_var'
-------------
Total:   2 lines
Violations: 2 lines
% Quality: 0%
-------------
```

**Comment by Bachmann1234** [comment]
PR up, I wanna see if I can fix 48 before releasing

**Comment by Bachmann1234** [comment]
Released! https://pypi.python.org/pypi/diff_cover/0.9.9

**Comment by Bachmann1234** [comment]
Thank you for finding this! Also thanks for the fantastic reproduction steps
