### ISSUE TITLE
diff-quality tries to check deleted files

### ISSUE THREAD

**Issue by fperrin** [Bachmann1234/diff-cover#48]
Hi,

When running `diff-quality --violations pyflakes --compare-branch master` (i.e. letting diff-quality run pyflakes itself), then if files have been deleted, diff-quality tries to run pyflakes on deleted files.

To reproduce:

```git clone git@github.com:fperrin/diff-cover-issue-demo.git
cd diff-cover-issue-demo/
git checkout try_deleted
diff-quality --violations pyflakes --compare-branch master```


This fails with pyflakes trying to parse hello.py, which has been deleted in branch try_deleted compared to master.

The following command returns the interesting files to check: `git diff --name-only --diff-filter=ACMR master..`; however:
* not sure how supported across git releases the above options are;
* this would require a second run of git to find the modified line offsets.

**Comment by Bachmann1234** [comment]
Same workaround for this one. 
 
Until I release a fix you can pass in a pre generated report

**Comment by Bachmann1234** [comment]
Fix Released https://pypi.python.org/pypi/diff_cover/0.9.9

**Comment by Bachmann1234** [comment]
Thank you for finding this! Also thanks for the fantastic reproduction steps

**Comment by fperrin** [comment]
Hi Matt,
Thanks for the fix and and for your reactivity. New version of diff-cover does fix the issue I was seeing in our repo, so looks good to me!
