### ISSUE TITLE
if this UT coverage tool can be use to c , c++ code?

### ISSUE THREAD

**Issue by pzh2386034** [Bachmann1234/diff-cover#59]
Question as title~~

**Comment by Bachmann1234** [comment]
It is possible. However, not at present.

As long as there is a coverage tool that produces cobertura reports. Then it can be integrated into diff-cover

**Comment by peterg79** [comment]
You can try converting your coverage file to cobertura format. There are several projects available for that, e.g. https://github.com/eriwen/lcov-to-cobertura-xml

**Comment by pzh2386034** [comment]
thanks
