### ISSUE TITLE
It isn't clear that edx/diff-cover is obsolete

### ISSUE THREAD

**Issue by nedbat** [Bachmann1234/diff-cover#6]
There are commits on edx/diff-cover since the shift over to this repo.  Those commits look like duplicates of ones made here.  There are also issues opened on the edx/diff-cover repo.  Shouldn't we close that repo completely?

**Comment by Bachmann1234** [comment]
Ive mostly left the edX repo alone. No more commits will be happening there. There was just a bit of a transition as I was unsure how that repo would be decommissioned. 

I will close the issues over there. Any future issues and PRs I will redirect to my repo. If edX wants to close the repo that is on them, the risk though is that outside resources link to the edX repo.

**Comment by Bachmann1234** [comment]
Closed the issues, no future commits will go there. 

Think that is all I can do. Thoughts?
