### ISSUE TITLE
Add support for pycodestyle (formerly known as pep8)

### ISSUE THREAD

**Issue by jmoldow** [Bachmann1234/diff-cover#63]
The `pep8` has been renamed to `pycodestyle` (https://pypi.python.org/pypi/pycodestyle). See https://github.com/PyCQA/pycodestyle/issues/466 for details. All development and new releases happen under that name. The `pep8` PyPI library is now essentially abandoned.

`diff-cover` should support running `pycodestyle`. But it may want to retain support for `pep8` if it wants to remain backwards-compatible.

**Comment by mayou36** [comment]
I think this issue is resolved. pycodestyle is working.

**Comment by hugovk** [comment]
Fixed in https://github.com/Bachmann1234/diff-cover/pull/67.
