### ISSUE TITLE
question regarding fair use of your open source code

### ISSUE THREAD

**Issue by markfink** [Bachmann1234/diff-cover#75]
thank you for releasing your code as open source - I find it quite useful.

I am the maintainer of the metrics package and I plan to use 120 lines of your code (parse_diff_lines) for the upcoming **metrics.gitinfo** plugin.

I see that you use apache 2.0 license so this should be compatible with the MIT license I use.

I am using parse_diff_lines from here:
https://github.com/Bachmann1234/diff-cover/blob/34c9c4c0801137413e9b955f40649a5c2c2ec724/diff_cover/diff_reporter.py

here is how I intend to use your code:
https://github.com/markfink/metrics.gitinfo/blob/master/metrics_gitinfo/git_diff_muncher.py

please let me know if you see any license (or other) issues how I use your code. Thank you.
-Mark

**Comment by Bachmann1234** [comment]
I don't have a problem with it. I'm not the only author but I am the only one closely watching this repo best I know. Maybe add a comment linking to the project for attribution (not to me. The project. Probably include the file and commit.)
