### ISSUE TITLE
New line in source text causing diff cover to report incorrectly

### ISSUE THREAD

**Issue by rishi05091989** [Bachmann1234/diff-cover#77]
Say, I have a cobertura report in the following format,
```xml
<?xml version="1.0"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage 
line-rate="0.33" lines-valid="6699" lines-covered="2179" branches-valid="393" branches-covered="165" branch-rate="0.42" complexity="0" version="1.0" timestamp="1531218279433">
    <sources>        
        <source>
            /apps/jenkins/src/main/scala
        </source>
    </sources>
</coverage>
```

The code at [1] is not stripping the source name before comparing with git diff. Due to this, diff cover is producing incorrect reports. Ideally, code at [1] should look like this,

```python
[clazz for clazz in classes if
             src_abs_path in [
                 self._to_unix_path(
                     os.path.join(
                         source.strip(' \t\n\r'),
                         clazz.get('filename')
                     )
                 ) for source in sources]]
```
Let me know if I need to create a PR.

[1] https://github.com/Bachmann1234/diff-cover/blob/master/diff_cover/violationsreporters/violations_reporter.py#L87

**Comment by rishi05091989** [comment]
@Bachmann1234 Can you take a look at this ? I am blocked due to this issue

**Comment by Bachmann1234** [comment]
Just released https://pypi.org/project/diff_cover/1.0.4/ to try and address this. Let me know if it worked out for you

**Comment by rishi05091989** [comment]
@Bachmann1234 Thanks, the new version worked. I really like diff-cover, it does its purpose well.
