### ISSUE TITLE
generator jacoco html report

### ISSUE THREAD

**Issue by zyyong** [Bachmann1234/diff-cover#80]
Hi,Thank you for your reply.
I use coverage generator is jacoco,want to create the coverage html report.But failed!

command line:
diff-cover app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml --html-report report.html --compare-branch=remote/v2.0.0

error info:
Traceback (most recent call last):
  File "/usr/local/bin/diff-cover", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/diff_cover/tool.py", line 348, in main
    exclude=arg_dict['exclude'],
  File "/Library/Python/2.7/site-packages/diff_cover/tool.py", line 267, in generate_coverage_report
    reporter = HtmlReportGenerator(coverage, diff, css_url=css_url)
UnboundLocalError: local variable 'coverage' referenced before assignment

**Comment by Bachmann1234** [comment]
Is it possible you could share the xml file? Diff-Cover is looking for lines with the xml attribute "line-rate" If you are hitting this error its a sign that the tool did not find any of these lines.

**Comment by zyyong** [comment]
Can this tool generate the android diff coverage ?

**Comment by zyyong** [comment]
Can this tool generate the android diff coverage ? I use jacoco generate the android coverage, somebody said that this tool coud not use in android.

**Comment by Bachmann1234** [comment]
@peterg79 added jacoco support! https://pypi.org/project/diff_cover/1.0.5/
