### ISSUE TITLE
"SyntaxError: invalid syntax" from running latest diff-cover

### ISSUE THREAD

**Issue by sgilroy** [Bachmann1234/diff-cover#95]
diff-cover just started failing in our CI environment, perhaps as a result of the latest release. The same command seemed to work yesterday. Note that the change I made that triggered the latest build did change coverage, and I have not tried to verify whether this error occurs with a different version of diff-cover or with the older version of my project.

```
Running "shell:diff-cover" (shell) task
Traceback (most recent call last):
  File "/usr/bin/diff-cover", line 9, in <module>
    load_entry_point('diff-cover==1.0.7', 'console_scripts', 'diff-cover')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/diff_cover/tool.py", line 18, in <module>
    from diff_cover.report_generator import (
  File "/usr/lib/python2.6/site-packages/diff_cover/report_generator.py", line 18
    violation.line for violation in violations
                     ^
SyntaxError: invalid syntax
```

**Comment by Bachmann1234** [comment]
Oh jeez. I'm sorry to cause you all issues on a weekend.... 

Im a bit shocked my CI did not catch this. Ill take a look right away... (I have to see if I still support python2.6 officially actually...)

**Comment by Bachmann1234** [comment]
Yeah, looking over this. I dropped 2.6 support a while back which would explain why CI would not have caught the error... though I am a tad skeptical that this is our first use of 2.6 invalid syntax. 

but let me do a quick check to confirm

**Comment by Bachmann1234** [comment]
Ok, yeah

So python2.6 support broke around november of 2017 and I decided it was not worth continuing to support it.

 https://github.com/Bachmann1234/diff-cover/commit/75efbbac12f38c0491b0cf738053e750113917fe#diff-b91f3d5bd63fcd17221b267e851608e8

If upgrading to 2.7 (or 3 <insert true but annoying pitch here>) is not an option try pinning to https://github.com/Bachmann1234/diff-cover/releases/tag/v1.0.6

Hope that helps!

**Comment by sgilroy** [comment]
@Bachmann1234 Sounds good. Thanks Matt! Someone else had updated the version of diff-cover (from some significantly earlier version) without me realizing it. The release of 1.0.7 seems to have just been a coincidence. Thanks for maintaining a great project that continues to be very valuable to our team!

**Comment by Bachmann1234** [comment]
This is a dead issue but talking somewhere I just realized there is a fairly easy work around if you wanted you update diff cover without updating your other python stuff

Diff cover is a tool not a library. So it's not like it would break your code to remove diff cover from the dependencies of your project and have a separate and more modern python interpreter installed just to run tools. 

Your call if it's worth it but just thought I'd put it here for the record
