### ISSUE TITLE
Run diff-cover error

### ISSUE THREAD

**Issue by sunmoondeer** [Bachmann1234/diff-cover#96]
os: windows 10
python version: 3.6.5
Installed with pip install diff_cover command

error info:
Traceback (most recent call last):
  File "D:\program\python\lib\site-packages\pkg_resources\__init__.py", line 346, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\program\python\Scripts\diff-cover-script.py", line 11, in <module>
    load_entry_point('diff-cover==1.0.7', 'console_scripts', 'diff-cover')()
  File "D:\program\python\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\program\python\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "D:\program\python\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "D:\program\python\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\program\python\lib\site-packages\diff_cover-1.0.7-py3.6.egg\diff_cover\tool.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "D:\program\python\lib\site-packages\diff_cover-1.0.7-py3.6.egg\diff_cover\report_generator.py", line 181, in <module>
  File "D:\program\python\lib\site-packages\jinja2\loaders.py", line 224, in __init__
    provider = get_provider(package_name)
  File "D:\program\python\lib\site-packages\pkg_resources\__init__.py", line 348, in get_provider
    __import__(moduleOrReq)
TypeError: __import__() argument 1 must be str, not None

**Comment by Bachmann1234** [comment]
This is string. I know people have been able to use this with windows in the past... Ill see if I can reproduce this... I think ill have some time tonight.

**Comment by Bachmann1234** [comment]
I had some trouble reproducing this.

I tried using a virtualenv in windows 10. I install diff cover and I am able to run diff-cover and diff-quality and the only errors I get are the expected validation error you would get when not providing any arguments.

```
λ virtualenv venv
Using base prefix 'c:\\users\\bachmann\\appdata\\local\\programs\\python\\python37-32'
New python executable in C:\Users\Bachmann\code\venv\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

C:\Users\Bachmann\code
λ venv\Scripts\
activate.bat          easy_install.exe      pip3.exe              wheel.exe
deactivate.bat        pip.exe               python.exe
easy_install-3.7.exe  pip3.7.exe            pythonw.exe
C:\Users\Bachmann\code
λ venv\Scripts\activate.bat

C:\Users\Bachmann\code
(venv) λ pip install diff-cover
Collecting diff-cover
  Downloading https://files.pythonhosted.org/packages/55/0d/3aab24b03c40957b93912cc41e511e1e4069e0c10c1b08418f20ea7e2966/diff_cover-1.0.7.tar.gz (74kB)
    100% |████████████████████████████████| 81kB 2.3MB/s
Collecting Jinja2>=2.7.1 (from diff-cover)
  Downloading https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl (124kB)
    100% |████████████████████████████████| 133kB 3.1MB/s
Collecting six>=1.6.1 (from diff-cover)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting jinja2_pluralize (from diff-cover)
  Downloading https://files.pythonhosted.org/packages/40/26/e6a6d7741076ea1bcfac02821e744fc40fa4cbb07e870b7dd969f4af8721/jinja2_pluralize-0.3.0-py2.py3-none-any.whl
Collecting pygments (from diff-cover)
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
    100% |████████████████████████████████| 849kB 4.9MB/s
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.1->diff-cover)
  Downloading https://files.pythonhosted.org/packages/5b/d4/1deb3c5dc3714fb160c7e2116fc6dff36a063d9156a9328cce54ef35cc52/MarkupSafe-1.1.1-cp37-cp37m-win32.whl
Collecting inflect>=0.2.4 (from jinja2_pluralize->diff-cover)
  Downloading https://files.pythonhosted.org/packages/86/02/e6b11020a9c37d25b4767a1d0af5835629f6e75d6f51553ad07a4c73dc31/inflect-2.1.0-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 51kB 3.9MB/s
Building wheels for collected packages: diff-cover
  Building wheel for diff-cover (setup.py) ... done
  Stored in directory: C:\Users\Bachmann\AppData\Local\pip\Cache\wheels\cc\3e\07\7d709018d2f36544630ef5f9de77e074cfca5f6ef7dcd2ca9d
Successfully built diff-cover
Installing collected packages: MarkupSafe, Jinja2, six, inflect, jinja2-pluralize, pygments, diff-cover
Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 diff-cover-1.0.7 inflect-2.1.0 jinja2-pluralize-0.3.0 pygments-2.3.1 six-1.12.0

C:\Users\Bachmann\code
(venv) λ diff-cover
usage: diff-cover [-h] [--html-report FILENAME] [--external-css-file FILENAME]
                  [--compare-branch BRANCH] [--fail-under SCORE]
                  [--ignore-staged] [--ignore-unstaged]
                  [--exclude EXCLUDE [EXCLUDE ...]]
                  [--src-roots DIRECTORY [DIRECTORY ...]]
                  coverage_xml [coverage_xml ...]
diff-cover: error: the following arguments are required: coverage_xml

C:\Users\Bachmann\code
(venv) λ diff-quality
usage: diff-quality [-h] --violations TOOL [--html-report FILENAME]
                    [--external-css-file FILENAME] [--compare-branch BRANCH]
                    [--options [OPTIONS]] [--fail-under SCORE]
                    [--ignore-staged] [--ignore-unstaged]
                    [--exclude EXCLUDE [EXCLUDE ...]]
                    [input_reports [input_reports ...]]
diff-quality: error: the following arguments are required: --violations
```

**Comment by sunmoondeer** [comment]
HI，


I update to the 1.0.7 and the problem is fixed. I have other problem, I generator the xml file by invoke jacoco API like 


final XMLFormatter xmlFormatter = new XMLFormatter();
final IReportVisitor xmlVisitor = xmlFormatter
    .createVisitor(new FileOutputStream("D:/work/test/jacoco/codecoverage/xxx/aaa.xml"));
  xmlVisitor.visitInfo(execFileLoader.getSessionInfoStore().getInfos(),
    execFileLoader.getExecutionDataStore().getContents());
  xmlVisitor.visitBundle(bundleCoverage, new DirectorySourceFileLocator(
    sourceDirectory, "utf-8", 4));
  xmlVisitor.visitEnd();


And I went to the D:/work/test/jacoco/codecoverage/xxx directoy run diff-cover command, I received 
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------

No lines with coverage information in this diff. This directory contains the source files


Where shoud i run the diff-cover command?





At 2019-04-08 04:37:37, "Matt Bachmann" <notifications@github.com> wrote:


I had some trouble reproducing this.

I tried using a virtualenv in windows 10. I install diff cover and I am able to run diff-cover and diff-quality and the only errors I get are the expected validation error you would get when not providing any arguments.

λ virtualenv venv

Using base prefix 'c:\\users\\bachmann\\appdata\\local\\programs\\python\\python37-32'

New python executable in C:\Users\Bachmann\code\venv\Scripts\python.exe

Installing setuptools, pip, wheel...

done.



C:\Users\Bachmann\code

λ venv\Scripts\

activate.bat          easy_install.exe      pip3.exe              wheel.exe

deactivate.bat        pip.exe               python.exe

easy_install-3.7.exe  pip3.7.exe            pythonw.exe

C:\Users\Bachmann\code

λ venv\Scripts\activate.bat



C:\Users\Bachmann\code

(venv) λ pip install diff-cover

Collecting diff-cover

  Downloading https://files.pythonhosted.org/packages/55/0d/3aab24b03c40957b93912cc41e511e1e4069e0c10c1b08418f20ea7e2966/diff_cover-1.0.7.tar.gz (74kB)

    100% |████████████████████████████████| 81kB 2.3MB/s

Collecting Jinja2>=2.7.1 (from diff-cover)

  Downloading https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl (124kB)

    100% |████████████████████████████████| 133kB 3.1MB/s

Collecting six>=1.6.1 (from diff-cover)

  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl

Collecting jinja2_pluralize (from diff-cover)

  Downloading https://files.pythonhosted.org/packages/40/26/e6a6d7741076ea1bcfac02821e744fc40fa4cbb07e870b7dd969f4af8721/jinja2_pluralize-0.3.0-py2.py3-none-any.whl

Collecting pygments (from diff-cover)

  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)

    100% |████████████████████████████████| 849kB 4.9MB/s

Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.1->diff-cover)

  Downloading https://files.pythonhosted.org/packages/5b/d4/1deb3c5dc3714fb160c7e2116fc6dff36a063d9156a9328cce54ef35cc52/MarkupSafe-1.1.1-cp37-cp37m-win32.whl

Collecting inflect>=0.2.4 (from jinja2_pluralize->diff-cover)

  Downloading https://files.pythonhosted.org/packages/86/02/e6b11020a9c37d25b4767a1d0af5835629f6e75d6f51553ad07a4c73dc31/inflect-2.1.0-py2.py3-none-any.whl (40kB)

    100% |████████████████████████████████| 51kB 3.9MB/s

Building wheels for collected packages: diff-cover

  Building wheel for diff-cover (setup.py) ... done

  Stored in directory: C:\Users\Bachmann\AppData\Local\pip\Cache\wheels\cc\3e\07\7d709018d2f36544630ef5f9de77e074cfca5f6ef7dcd2ca9d

Successfully built diff-cover

Installing collected packages: MarkupSafe, Jinja2, six, inflect, jinja2-pluralize, pygments, diff-cover

Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 diff-cover-1.0.7 inflect-2.1.0 jinja2-pluralize-0.3.0 pygments-2.3.1 six-1.12.0



C:\Users\Bachmann\code

(venv) λ diff-cover

usage: diff-cover [-h] [--html-report FILENAME] [--external-css-file FILENAME]

                  [--compare-branch BRANCH] [--fail-under SCORE]

                  [--ignore-staged] [--ignore-unstaged]

                  [--exclude EXCLUDE [EXCLUDE ...]]

                  [--src-roots DIRECTORY [DIRECTORY ...]]

                  coverage_xml [coverage_xml ...]

diff-cover: error: the following arguments are required: coverage_xml



C:\Users\Bachmann\code

(venv) λ diff-quality

usage: diff-quality [-h] --violations TOOL [--html-report FILENAME]

                    [--external-css-file FILENAME] [--compare-branch BRANCH]

                    [--options [OPTIONS]] [--fail-under SCORE]

                    [--ignore-staged] [--ignore-unstaged]

                    [--exclude EXCLUDE [EXCLUDE ...]]

                    [input_reports [input_reports ...]]

diff-quality: error: the following arguments are required: --violations

**Comment by sunmoondeer** [comment]
I update to the 1.0.7 version, and this problem fixed. 
Thanks
