### ISSUE TITLE
jacoco - No lines with coverage information in this diff

### ISSUE THREAD

**Issue by dknebula** [Bachmann1234/diff-cover#99]
use the following command, prompt "No lines with coverage information in this diff."

`diff-cover coverage.xml --compare-branch=origin/develop`

> Diff Coverage
> Diff: origin/develop...HEAD, staged and unstaged changes
> No lines with coverage information in this diff.

**Comment by sunmoondeer** [comment]
Can you get the diff info  when you run git diff origin/develop...HEAD?

**Comment by dknebula** [comment]
> Can you get the diff info when you run git diff origin/develop...HEAD?

I can get the diff info when run the command.
`git diff origin/develop...HEAD`

> diff --git a/.gitignore b/.gitignore
> index fa77f99..f9d929a 100644
> ...

**Comment by dknebula** [comment]
> Can you get the diff info when you run git diff origin/develop...HEAD?

I can get the diff info when run the command.

`git diff origin/develop...HEAD`

> ...
> @@ -265,15 +265,30 @@ 
> ...

**Comment by sunmoondeer** [comment]
This tool just work on linux env right now, if you are using windows then change to linux

**Comment by Bachmann1234** [comment]
im surprised to hear that. I have run the test suite in a windows environment in the past and it seemed to work. At some point I need to look into https://github.com/Bachmann1234/diff-cover/issues/103 and see if that shakes out any issues

**Comment by Bachmann1234** [comment]
https://github.com/Bachmann1234/diff-cover/pull/111 may help solve this. Im going to put out a release asap with it

**Comment by Bachmann1234** [comment]
Please try out https://pypi.org/project/diff-cover/2.1.0/

**Comment by keyescgm** [comment]
> Please try out https://pypi.org/project/diff-cover/2.1.0/

How to view the diff-cover‘s version?

**Comment by keyescgm** [comment]
hello，you see，my project Integrated jacoco plugin

![image](https://user-images.githubusercontent.com/9543572/59479629-51c7e380-8e90-11e9-8033-c13b04ad5949.png)

use the following command, prompt "No lines with coverage information in this diff."

![image](https://user-images.githubusercontent.com/9543572/59479697-850a7280-8e90-11e9-9489-2460ee9cb73b.png)

**Comment by Bachmann1234** [comment]
i'm embarrassed to say diff-cover does not have a `--version`

I will make a note to add that. 

If you installed the package via `pip` you can run `pip freeze` to see what you have installed.

Looking at your screenshots I think you may be having a similar issue to https://github.com/Bachmann1234/diff-cover/issues/114 

Since you are on windows I would suggest making sure you are up to date. 

In addition, look at the `--src-roots` command line switch

**Comment by keyescgm** [comment]
how to add the --src-roots？
![image](https://user-images.githubusercontent.com/9543572/59480367-efbcad80-8e92-11e9-8fef-8f5ad585bef8.png)

**Comment by Bachmann1234** [comment]
```
  --src-roots DIRECTORY [DIRECTORY ...]
                        List of source directories (only for jacoco coverage
                        reports)
```

take your command and tell `diff-cover` the the location of your src directories

by default it assumes your code is in `'src/main/java'` and `'src/test/java'` 

but it looks like you have a multi module build. So you need to add more. So you need to specify them.

So I think you need (in addition to your other options) 

`--src-roots "/module/<blanked out I cant tell>" --src-roots "/app/src/main/java" --src-roots "/src/test/java"`

**Comment by keyescgm** [comment]
> i'm embarrassed to say diff-cover does not have a `--version`
> 
> I will make a note to add that.
> 
> If you installed the package via `pip` you can run `pip freeze` to see what you have installed.
> 
> Looking at your screenshots I think you may be having a similar issue to #114
> 
> Since you are on windows I would suggest making sure you are up to date.
> 
> In addition, look at the `--src-roots` command line switch

![image](https://user-images.githubusercontent.com/9543572/59480995-327f8500-8e95-11e9-8e05-c1566afeb7da.png)

**Comment by keyescgm** [comment]
how can i do?
always show the result：
No lines with coverage information in this diff.
headache··
I've tried all methods

**Comment by dknebula** [comment]
@Bachmann1234 @sunmoondeer  thanks for your help.

There are several modules in my project. 
<pre>
.
├── module1
│   ├── pom.xml
│   └── src
│       └── main
│           └── java
├── module2
│   ├── pom.xml
│   └── src
│       └── main
│           └── java
├── pom.xml
</pre>

Although I can not get the whole diff info directly, I can get the module diff in the project.

`diff-cover coverage.xml`

> Diff Coverage
> Diff: origin/master...HEAD, staged and unstaged changes
> No lines with coverage information in this diff.

`diff-cover coverage.xml --src-roots module1/src/main/java`

> ...
> Total:   188 lines
> Missing: 107 lines
> Coverage: 43%
